version: '3.8'

services:
  db:
    image: postgres:15
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    image: toufikj/strapi:latest
    container_name: strapi-app
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db                     # <-- important: matches service name
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - .:/app
      - strapi_node_modules:/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - db
    networks:
      - strapi-net

  nginx:
    image: nginx:latest
    container_name: strapi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - strapi
    networks:
      - strapi-net

volumes:
  db-data:
  strapi_node_modules:

networks:
  strapi-net:
    driver: bridge
