name: Build and Push Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      dockerhub-username:
        description: 'Docker Hub Username'
        required: true
        type: string
        default: toufikj
      dockerhub-repository:
        description: 'Docker Hub Repository Name'
        required: true
        type: string
        default: strapi
      dockerfile-path:
        description: 'Path to Dockerfile'
        required: true
        type: string
        default: ./my-strapi-app/


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          tags: ${{ inputs.dockerhub-username }}/${{ inputs.dockerhub-repository }}:${{ github.run_number }}
