name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      ecr-registry:
        description: 'The Amazon ECR registry URL'
        required: true
        type: string
        default: "607700977843.dkr.ecr.us-east-2.amazonaws.com/toufikj-strapi"
      ecr-repository:
        description: 'The Amazon ECR repository name'
        required: true
        type: string
        default: toufikj-strapi
      aws-region:
        description: 'The AWS region'
        required: true
        type: string
        default: us-east-2
      dockerfile-path:
        description: 'The path to the Dockerfile'
        required: true
        type: string
        default: ./my-strapi-app/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.dockerfile-path }}
          file: ${{ inputs.dockerfile-path }}/Dockerfile
          push: true
          build-args: |
            DATABASE_HOST=${{ secrets.DB_HOST }}
            DATABASE_PASSWORD=${{ secrets.DB_PASS }}
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:${{ github.run_number }}
            ${{ steps.ecr-login.outputs.registry }}/${{ inputs.ecr-repository }}:latest
